openapi: 3.0.0
info:
  title: Whatsapp Template message generator
  version: 1.0.0
servers:
  - url: https://ajrbr73v5ylfwa7bfkox447rni0dbvis.lambda-url.ap-south-1.on.aws
  - url: https://kdq2lwhibkthomlf33pbdd52uy0lcfqu.lambda-url.ap-south-1.on.aws
paths:
  /whatsapp-template:
    post:
      tags:
        - General
      summary: prod
      description: >-
        ### POST /health-check


        A function that prints and returns the attributes passed in the prompt.


        #### Request Body


        `{ Same as /whatsapp-template}`


        #### Response (JSON Schema)


        ``` json

        {"message":"Attributes printed in console, {'DB': 'qdrant', 'TOPK': 10,
        'user_name': '', 'contact': '', 'email_id': '', 'template_category':
        'Authentication', 'template_language': 'English', 'message_input': 'OTP
        for login into cyber systems user panel.', 'optimization_choice': 'Click
        Rate', 'mood': 'Happy', 'style': '', 'emoji': True}"}

         ```

        ### POST /whatsapp-template


        #### Request Body


        - `data` (object)
            
            - `Records` (array)
                
                - `body` (object)
                    
                    - `template_category` (string)
                        
                    - `template_language` (string)
                        
                    - `message_input` (string)
                        
                    - `optimization_choice` (string)
                        
                    - `mood` (string)
                        
                    - `user_name` (Optional: string)
                        
                    - `contact` (Optional: string)
                        
                    - `email_id` (Optional: string)
                        
                    - `style` (Optional: string)
                        
                    - `emoji` (Optional: boolean)
                        
                    - `DB` (Optional: string = **"qdrant"** | "pinecone"
                        
                    - `TOPK` (Optional: int = 10)
                        

        #### Response (JSON Schema)


        The response will contain the generated whatsapp template.


        ``` json

        {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }

         ```
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                data:
                  Records:
                    - body:
                        template_category: Marketing
                        template_language: English
                        message_input: sale on cooler
                        optimization_choice: Click Rate
                        mood: Funny
                        rate_limit: false
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
